import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ndvy_player/src/access_unit_pts.dart';
import 'package:ndvy_player/src/decoder/h264_baseline_idr_decoder.dart';
import 'package:ndvy_player/src/decoder/slice_header.dart';
import 'package:ndvy_player/src/pes_pts.dart';
import 'package:ndvy_player/src/ts_packets.dart';
import 'package:ndvy_player/src/ts_pes.dart';
import 'package:ndvy_player/src/ts_psi.dart';

const _fixture = 'test/fixtures/hls/mux_x36xhzz/low_320x184_segment_000.ts';

void main() {
  test(
    'decodes the Mux 320x184 multi-reference segment pixel-exactly',
    () {
      final bytes = File(_fixture).readAsBytesSync();
      expect(
        sha256.convert(bytes).toString(),
        'b82fcf4dbcec2d8fab7d94bdd48b070aa6e74d7240b1965a0b28c128d6858477',
      );

      final packets = parseTsPackets(bytes).toList(growable: false);
      final pat = TsPat.find(packets);
      expect(pat, isNotNull);
      final pmt = TsPmt.find(packets, pat!.programs.values.single);
      expect(pmt, isNotNull);
      final videoPid = pmt!.streams
          .singleWhere((stream) => stream.streamType == 0x1b)
          .pid;

      final chunks = <PtsChunk>[];
      int? basePts90k;
      for (final pesBytes in assemblePesPackets(packets, videoPid)) {
        final pes = parsePes(pesBytes);
        expect(pes, isNotNull);
        basePts90k ??= pes!.pts90k;
        chunks.add(PtsChunk(pts90k: pes!.pts90k, payload: pes.esPayload));
      }
      final accessUnits = buildTimestampedAccessUnitsFromPtsChunks(
        ptsChunks: chunks,
        basePts90k: basePts90k,
      );
      expect(accessUnits, hasLength(300));
      expect(accessUnits.first.ptsMs, 0);
      expect(accessUnits[2].ptsMs, 67);
      expect(accessUnits.last.ptsMs, closeTo(9967, 1));

      final decoder = H264BaselineDecoder();
      final decodedSequence = BytesBuilder(copy: false);
      for (var index = 0; index < accessUnits.length; index++) {
        final accessUnit = accessUnits[index];
        final frame = decoder.decodeAccessUnit(accessUnit.nals);
        expect(
          frame,
          isNotNull,
          reason:
              'Mux picture $index @ ${accessUnit.ptsMs}ms failed: '
              '${decoder.lastError}',
        );
        expect(frame!.width, 320);
        expect(frame.height, 184);
        decodedSequence
          ..add(frame.y)
          ..add(frame.u)
          ..add(frame.v);

        if (index == 2) {
          final slice = accessUnit.nals.singleWhere(
            (nal) => nal.isNotEmpty && (nal.first & 0x1f) == 1,
          );
          final header = parseSliceHeader(
            slice,
            ppsById: decoder.pictureParameterSets,
            spsById: decoder.sequenceParameterSets,
          );
          expect(header.numRefIdxL0ActiveMinus1 + 1, 2);
          expect(header.frameNum, 2);
        }
      }

      // Independently generated by FFmpeg as cropped planar I420 for all 300
      // frames. This catches wrong reference selection as well as bit parsing.
      expect(
        sha256.convert(decodedSequence.takeBytes()).toString(),
        'dce6f07c2d502b9ccde7ea41a4095261fea7957f1b04d4c845cbd827226641ec',
      );
      expect(decoder.sequenceParameterSets.values.single.maxNumRefFrames, 5);
    },
    timeout: const Timeout(Duration(minutes: 2)),
  );
}
